---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mesh.t7d.io.github.com
  resources:
  - servicecontrols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.t7d.io.github.com
  resources:
  - servicecontrols/finalizers
  verbs:
  - update
- apiGroups:
  - mesh.t7d.io.github.com
  resources:
  - servicecontrols/status
  verbs:
  - get
  - patch
  - update
