# permissions for end users to view servicecontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicecontrol-viewer-role
rules:
- apiGroups:
  - mesh.t7d.io.github.com
  resources:
  - servicecontrols
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.t7d.io.github.com
  resources:
  - servicecontrols/status
  verbs:
  - get
